<?php
namespace app\controllers;

use app\models\Call;
use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;

class CallController extends ActiveController
{

    public function beforeAction($action)
    {
        header('Access-Control-Allow-Origin: *');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public $modelClass = 'app\models\Call';

}
