<?php
namespace app\controllers;
use yii\rest\ActiveController;

class TypeOfProblemController extends ActiveController
{

    public function beforeAction($action) //костыль для обхода CORS
    {
        header('Access-Control-Allow-Origin: *');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public $modelClass = 'app\models\TypeOfProblem';
}