<?php

namespace app\widgets;

use app\models\Customer;
use yii\base\Widget;
use yii\helpers\Html;
use app\models\Call;

class ReviewItem extends \yii\base\Widget
{

public $post;
public $name;
public $text;
public $image;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
//        $this->image = Customer::findOne($this->image)->brandName;
        //$this->model->customer = Customer::findOne($this->model->customer)->brandName;
    }

    public function run()
    {
        return $this->render('reviewitem', [
            'name' => $this->name, 'text' => $this->text, 'post' => $this->post, 'image' => $this->image,
        ]);
    }

}