<?php

namespace app\widgets;

use app\models\Customer;
use yii\base\Widget;
use yii\helpers\Html;
use app\models\Call;

class SmiReviewItem extends \yii\base\Widget
{

    public $title;
    public $date;
    public $link;
    public $image;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
//        $this->customer = Customer::findOne($this->customer)->brandName;
        //$this->image = $this->image->one()->filename;
        //$this->model->customer = Customer::findOne($this->model->customer)->brandName;
    }

    public function run()
    {
        return $this->render('smireviewitem', [
            'title' => $this->title, 'date' => $this->date, 'link' => $this->link, 'image' => $this->image,
        ]);
    }

}